version: '2'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "35729:35729"
    volumes:
      - ".:/opt/web"
    links:
      - database
    command: "bash"

  database:
    image: mongo
    volumes:
      - ".:/opt/database"
